### ISSUE TITLE
Integrate OpenAI API 

### ISSUE THREAD

**Issue by davidtcalabrese** [mad-ent-java-s22/indie-project#13]
Ideally I would like to be able to give users the option of having a blog post written for them using AI. All they would have to do is choose a topic(s). Then I would send a request to the OpenAI API to "write a blog post about " + topics. 

Here's an example request & response (in plain language).

* User chooses "sports" and "politics".
* The following prompt is generated and sent to the API: `Write a blog post about sports and politics.`
* This is what was returned:

> In recent years, there has been an increasing trend of athletes using their platform to speak out on political and social issues. From Colin Kaepernick taking a knee during the National Anthem to LeBron James opening up a school for underprivileged children, it is clear that sports and politics are becoming increasingly intertwined.

> Some people argue that athletes should stick to sports and leave the politics to the politicians. However, given the reach and influence that athletes have, many believe that they have a responsibility to use their platform to effect change.

> Whether you believe that athletes should get involved in politics or not, there is no denying that the world of sports is changing. As we continue to see athletes using their voices to speak out on the issues that matter to them, it is clear that the relationship between sports and politics is only going to become more complex.

**Comment by davidtcalabrese** [comment]
API working, tests passing, need to integrate in app

**Comment by davidtcalabrese** [comment]
getting this error when I submit the API request

```
21-Apr-2022 19:12:45.092 SEVERE [http-nio-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke 
Servlet.service() for servlet [GeneratePost] in context with path [] threw exception
	java.lang.NullPointerException: Parameter specified as non-null is null:
        method okhttp3.Request$Builder.addHeader, parameter value
    at okhttp3.Request$Builder.addHeader(Request.kt)
    at org.davidcalabrese.services.OpenAIService.getPostOnTopic(OpenAIService.java:96)
    at org.davidcalabrese.controller.GeneratePost.doPost(GeneratePost.java:46)
    at javax.servlet.http.HttpServlet.serviceHttpServlet.java:681) 
    ...
```

not sure why this is working in the test but not in the app. The headers I'm adding are "Authorization" (value is bearer token) and "Content-Type" (value is "application/json").

**Comment by davidtcalabrese** [comment]
Figured it out!

I did not have the api.properties file in my main/resources directory. I should have figured this out right away by reading the logs.

**Comment by davidtcalabrese** [comment]
API is integrated!
